### ISSUE TITLE
"KeyError: 'unsupported_platform_for_package'" when installing a wagon on the wrong platform

### ISSUE THREAD

**Issue by OddBloke** [cloudify-cosmo/wagon#59]
```
+ wagon install -s foo-0.1.0-py27-none-manylinux1_x86_64-Ubuntu-precise.wgn
INFO - Installing foo-0.1.0-py27-none-manylinux1_x86_64-Ubuntu-precise.wgn
ERROR - Platform unsupported for package (linux_x86_64).
Traceback (most recent call last):
  File "/srv/jenkins/jobs/TEMP-Wagon-Test/workspace/wagon_venv/bin/wagon", line 11, in <module>
    sys.exit(main())
  File "/srv/jenkins/jobs/TEMP-Wagon-Test/workspace/wagon_venv/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/srv/jenkins/jobs/TEMP-Wagon-Test/workspace/wagon_venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/srv/jenkins/jobs/TEMP-Wagon-Test/workspace/wagon_venv/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/jenkins/jobs/TEMP-Wagon-Test/workspace/wagon_venv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/jenkins/jobs/TEMP-Wagon-Test/workspace/wagon_venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/srv/jenkins/jobs/TEMP-Wagon-Test/workspace/wagon_venv/local/lib/python2.7/site-packages/wagon/wagon.py", line 519, in install
    virtualenv, requirements_file, upgrade, ignore_platform, install_args)
  File "/srv/jenkins/jobs/TEMP-Wagon-Test/workspace/wagon_venv/local/lib/python2.7/site-packages/wagon/wagon.py", line 180, in install
    sys.exit(codes.errors['unsupported_platform_for_package'])
KeyError: 'unsupported_platform_for_package'
```

**Comment by nir0s** [comment]
The way we do error handling has changed. This is no longer relevant.
